"""add milestone_id to transactions

Revision ID: 96d70e5aeaa7
Revises: a2588880fd8a
Create Date: 2026-05-20 03:38:13.444594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d70e5aeaa7'
down_revision = 'a2588880fd8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'milestones', ['milestone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('milestone_id')

    # ### end Alembic commands ###
