"""initial schema

Revision ID: a2588880fd8a
Revises: 
Create Date: 2026-05-19 03:02:00.447375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2588880fd8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('project_type', sa.Text(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('total_budget_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sanctioned_loan_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('rera_registration_number', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('work_package', sa.Text(), nullable=True),
    sa.Column('contract_amount_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('retention_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_heads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('budgeted_amount_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draw_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('reporting_period_start', sa.Date(), nullable=True),
    sa.Column('reporting_period_end', sa.Date(), nullable=True),
    sa.Column('total_draw_amount_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('overall_completion_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bank_format', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('pdf_s3_key', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('marked_by', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disbursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('draw_report_id', sa.UUID(), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cumulative_drawn_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bank_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draw_report_id'], ['draw_reports.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draw_report_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draw_report_id', sa.UUID(), nullable=False),
    sa.Column('cost_head_id', sa.UUID(), nullable=False),
    sa.Column('budgeted_amount_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('spent_to_date_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('draw_amount_due_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('previously_drawn_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('balance_to_draw_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cost_head_id'], ['cost_heads.id'], ),
    sa.ForeignKeyConstraint(['draw_report_id'], ['draw_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('cost_head_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor_name', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.Text(), nullable=True),
    sa.Column('gst_amount_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tds_amount_inr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('raw_line_item', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['cost_head_id'], ['cost_heads.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('draw_report_line_items')
    op.drop_table('disbursements')
    op.drop_table('milestones')
    op.drop_table('draw_reports')
    op.drop_table('cost_heads')
    op.drop_table('contractors')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('organisations')
    # ### end Alembic commands ###
